# Generated by Django 3.1.5 on 2022-02-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_id', models.CharField(max_length=100)),
                ('date_purchase', models.DateField()),
                ('customer_id', models.BigIntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('vehicle_segment', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bodily_injury', models.CharField(max_length=100)),
                ('personal_injury_protection', models.CharField(max_length=100)),
                ('property_damage_liability', models.CharField(max_length=100)),
                ('collision', models.CharField(max_length=100)),
                ('comprehensive', models.CharField(max_length=100)),
                ('customer_gender', models.CharField(max_length=100)),
                ('customer_income_group', models.CharField(max_length=256)),
                ('customer_region', models.CharField(max_length=100)),
                ('customer_marital_status', models.CharField(max_length=100)),
            ],
        ),
    ]
