# Generated by Django 3.1.5 on 2022-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='bodily_injury',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='collision',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='comprehensive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='customer_marital_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='personal_injury_protection',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='property_damage_liability',
            field=models.BooleanField(),
        ),
    ]
