# Generated by Django 3.1.5 on 2022-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220204_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_id',
            field=models.BigIntegerField(),
        ),
    ]
